Models/PiggyBankContext.cs
﻿using Microsoft.EntityFrameworkCore;

namespace PiggyBank.Models
{
    public class PiggyBankContext : DbContext
    {

        public PiggyBankContext(DbContextOptions<PiggyBankContext> options)
            : base(options) { }

        //Should be a dbset, not a property
        public virtual DbSet<SavingsGoal> SavingsGoals {get; set;}
       
    }

    
}

Models/SavingsGoal.cs
using System.ComponentModel.DataAnnotations;

namespace PiggyBank.Models
{
    public class SavingsGoal
    {
        [Key]
        [Required]
        public int ID { get; set; }
        public string Title { get; set; }
        [Required]
        public float GoalPrice { get; set; }
        public string Description { get; set; }
        public string LinkToPage { get; set; }
        public string LinkToImage { get; set; }
    }
}

Controllers/SavingsGoalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PiggyBank.Models;

namespace PiggyBank.Controllers
{
    public class SavingsGoalsController : Controller
    {
        private readonly PiggyBankContext _context;

        public SavingsGoalsController(PiggyBankContext context)
        {
            _context = context;
        }

        // GET: SavingsGoals
        public async Task<IActionResult> Index()
        {
            return View(await _context.SavingsGoals.ToListAsync());
        }

        // GET: SavingsGoals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savingsGoal = await _context.SavingsGoals
                .FirstOrDefaultAsync(m => m.ID == id);
            if (savingsGoal == null)
            {
                return NotFound();
            }

            return View(savingsGoal);
        }

        // GET: SavingsGoals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SavingsGoals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,GoalPrice,Description,LinkToPage,LinkToImage")] SavingsGoal savingsGoal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(savingsGoal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(savingsGoal);
        }

        // GET: SavingsGoals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savingsGoal = await _context.SavingsGoals.FindAsync(id);
            if (savingsGoal == null)
            {
                return NotFound();
            }
            return View(savingsGoal);
        }

        // POST: SavingsGoals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,GoalPrice,Description,LinkToPage,LinkToImage")] SavingsGoal savingsGoal)
        {
            if (id != savingsGoal.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(savingsGoal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SavingsGoalExists(savingsGoal.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(savingsGoal);
        }

        // GET: SavingsGoals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savingsGoal = await _context.SavingsGoals
                .FirstOrDefaultAsync(m => m.ID == id);
            if (savingsGoal == null)
            {
                return NotFound();
            }

            return View(savingsGoal);
        }

        // POST: SavingsGoals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var savingsGoal = await _context.SavingsGoals.FindAsync(id);
            _context.SavingsGoals.Remove(savingsGoal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SavingsGoalExists(int id)
        {
            return _context.SavingsGoals.Any(e => e.ID == id);
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PiggyBank.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using PiggyBank.Models;

namespace PiggyBank.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return Redirect("~/Views/SavingsGoals/Index.cshtml");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PiggyBank.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page

@{
    ViewData["Title"] = "Home page";
}

<body>
    <div class="text-center">
        <p>Check you account balance and savings goals below</p>
    </div>
    <div class="container mt-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Your Account Balance</h5>
                <p class="card-text">
                    Available Balance:
                    <span class="card-number font-weight-bolder text-success">$1,234.56</span>
                </p>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Your Savings Goals</h5>
                <div class="container mt-4">
 
            </div>
        </div>
    </div>
</body>

<script>
    // Redirect to the desired page
    window.location.replace("https://localhost:44331/SavingsGoals");
</script>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PiggyBank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="SavingsGoals" asp-action="Index">PiggyBank</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="SavingsGoals" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PiggyBank - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/SavingsGoals/Create.cshtml
@model PiggyBank.Models.SavingsGoal

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>SavingsGoal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Title</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GoalPrice" class="control-label">Goal Price</label>
                <input asp-for="GoalPrice" class="form-control" />
                <span asp-validation-for="GoalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkToPage" class="control-label">Link to page</label>
                <input asp-for="LinkToPage" class="form-control" />
                <span asp-validation-for="LinkToPage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkToImage" class="control-label">Link to image</label>
                <input asp-for="LinkToImage" class="form-control" />
                <span asp-validation-for="LinkToImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SavingsGoals/Delete.cshtml
@model PiggyBank.Models.SavingsGoal

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SavingsGoal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GoalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GoalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkToPage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkToPage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkToImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkToImage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/SavingsGoals/Details.cshtml
@model PiggyBank.Models.SavingsGoal

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>SavingsGoal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GoalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GoalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkToPage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkToPage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkToImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkToImage)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/SavingsGoals/Edit.cshtml
@model PiggyBank.Models.SavingsGoal

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>SavingsGoal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GoalPrice" class="control-label"></label>
                <input asp-for="GoalPrice" class="form-control" />
                <span asp-validation-for="GoalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkToPage" class="control-label"></label>
                <input asp-for="LinkToPage" class="form-control" />
                <span asp-validation-for="LinkToPage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkToImage" class="control-label"></label>
                <input asp-for="LinkToImage" class="form-control" />
                <span asp-validation-for="LinkToImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SavingsGoals/Index.cshtml
@model IEnumerable<PiggyBank.Models.SavingsGoal>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<body onload="savings()">
    <div class="text-center">
        <h1 class="display-4">Good Morning, Bobby</h1>
        <p>Check you account balance and savings goals below</p>
    </div>
    <div class="container mt-4">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Your Account Balance</h1>
                <p class="card-text">
                    Available Balance:
                    <span class="card-number font-weight-bolder text-success">$<span id="availablebalance">1,234.56</span></span>
                </p>
                <a asp-action="" id="depositAllowance" onclick="addFunds(); return false;" class="btn btn-success">
                    Deposit Allowance +
                </a>
            </div>
        </div>
        <br/>
        <div class="card">
            <div class="card-body">
                <h1>Your Savings Goals</h1>
                @foreach (var item in Model)
                {
                    <div class="card model">
                        <div class="card-body">
                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>
                            <p class="card-text">
                                Cost: $<span id="goalPrice" class="card-number font-weight-bold goalPrice">@Html.DisplayFor(modelItem => item.GoalPrice)</span>
                                <br/>
                                @Html.DisplayFor(modelItem => item.Description)
                            </p>
                            <p class="card-text">
                                Available Balance:
                                <span class="card-number font-weight-bolder text-success">$<span id="accountBalance" class="accountBalance">1,234.56</span></span>
                            </p>
                            <div id="myProgress" class="myProgress">
                                <div id="myBar" class="myBar">0%</div>
                            </div> 

                            <img src="@item.LinkToImage)" />
                            <br/>
                            <a asp-action="" class="btn btn-success">
                                Purchase -
                            </a>
                            <p>
                                <div class="row">
                                    <a asp-action="Edit" asp-route-id="@item.ID" class="pl-4 pr-4">Edit</a>  |
                                    <a asp-action="Details" asp-route-id="@item.ID" class="pl-4 pr-4">Details</a> | 
                                    <a asp-action="Delete" asp-route-id="@item.ID" class="pl-4">Delete</a>
                                </div>
                            </p>
                
                
                        </div>
                    </div>

                }
                <br />

                <a asp-action="Create" class="btn btn-success">
                Add a Savings Goal
                </a>
            </div>
        </div>
    </div>
</body>

<script>
    function savings()
    {
        console.log("savings is running");
        for (let iCount = 0; iCount < document.getElementsByClassName("card model").length; iCount++) {
            var i = 0;
            function move() {
                if (i == 0) {
                    i += 1;
                    var elem = document.getElementById("myBar");
                    var width = 10;
                    var id = setInterval(frame, 10);
                    function frame() {
                        if (width >= 100) {
                            clearInterval(id);
                            i = 0;
                        } else {
                            width++;
                            elem.style.width = width + "%";
                            elem.innerHTML = width + "%";
                        }
                    }
                }
            }

            document.getElementsByClassName("accountBalance")[iCount].innerHTML = document.getElementById("availablebalance").innerHTML

            // Get the Available Balance and GoalPrice values
            var availableBalance = parseFloat(document.getElementsByClassName("accountBalance")[iCount].innerHTML.replace(",", "")); // You can replace this with the actual available balance value
            var goalPrice = parseFloat(document.getElementsByClassName("card-number font-weight-bold goalPrice")[iCount].innerHTML); // Get the goal price from your ASP.NET model

            // Calculate the percentage
            console.log(availableBalance)
            var percentage = (availableBalance / goalPrice) * 100;

            // Set the percentage as innerHTML of the "myBar" element
            var myBar = document.getElementsByClassName("myBar")[iCount];
            if (percentage >= 100) {
                myBar.style.width = "100%";
                myBar.innerHTML = "100%";
            }
            else {
                myBar.style.width = percentage + "%";
                myBar.innerHTML = percentage.toFixed(2) + "%"; // Use toFixed(2) to format the percentage with 2 decimal places
            }
        };
    };

    function addFunds() {
        var parentPassword = prompt("What is the parent password?\n(Entering the password will add $100 to Bobby's available funds)").toLowerCase();

        // Check if the entered password is correct (you can replace 'parent' with the actual parent password)
        if (parentPassword === "parent") {
            // Password is correct, proceed with the deposit
            var currentBalanceElement = document.getElementById("availablebalance");
            var currentBalance = parseFloat(currentBalanceElement.innerHTML.replace(",", ""));
            console.log(currentBalance)
            // Increase the account balance by $100
            currentBalance += 100;
            currentBalanceElement.innerHTML = currentBalance.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");

            savings();
        } 
        else {
            // Password is incorrect, you can display an error message or take other actions
            alert("Incorrect parent password. Please try again.");
        }
    };
</script>


<style>
    #myProgress {
        width: 90%;
        background-color: grey;
    }

    #myBar {
        width: 0%;
        height: 30px;
        background-color: #04AA6D;
        text-align: center; /* To center it horizontally (if you want) */
        line-height: 30px; /* To center it vertically */
        color: white;
    }
</style>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PiggyBank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PiggyBank</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="SavingsGoals" asp-action="Index">View Goals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PiggyBank - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>